Ext.define('mobndf.view.Entries', {
  extend: 'Ext.Container',
  xtype: 'entries',
  config: {
    title: 'Notes de frais',
    padding:20,
    scrollable:true,
    layout: {
      type:'vbox',
      pack:'top',
      align:'stretch'
    },
    items : [
      {
        xtype : 'button',
        id : 'btnNewExp',
        text : 'Nouvelle note de frais',
        iconCls : 'compose'
      },
      {
        xtype : 'button',
        id : 'btnWaitingExp',
        text : 'En attente',
        iconCls : 'list'
      },
      {
        xtype : 'button',
        id : 'btnSearchExp',
        text : 'Recherche',
        iconCls : 'search'
      },
      {
        xtype : 'button',
        id : 'btnDashboard',
        text : 'Tableaux de bord',
        iconCls : 'icon-chart'
      },
      {
        xtype : 'button',
        id : 'btnMyProfile',
        text : 'Mon profil',
        iconCls : 'icon-user'
      },
{ xtype :'button', text :'anchor', iconCls:'icon-anchor' },
{ xtype :'button', text :'box', iconCls:'icon-box' },
{ xtype :'button', text :'upload', iconCls:'icon-upload' },
{ xtype :'button', text :'forbidden', iconCls:'icon-forbidden' },
{ xtype :'button', text :'lightning', iconCls:'icon-lightning' },
{ xtype :'button', text :'rss', iconCls:'icon-rss' },
{ xtype :'button', text :'team', iconCls:'icon-team' },
{ xtype :'button', text :'help', iconCls:'icon-help' },
{ xtype :'button', text :'info', iconCls:'icon-info' },
{ xtype :'button', text :'attachment', iconCls:'icon-attachment' },
{ xtype :'button', text :'heart', iconCls:'icon-heart' },
{ xtype :'button', text :'list', iconCls:'icon-list' },
{ xtype :'button', text :'music', iconCls:'icon-music' },
{ xtype :'button', text :'table', iconCls:'icon-table' },
{ xtype :'button', text :'folder', iconCls:'icon-folder' },
{ xtype :'button', text :'pencil', iconCls:'icon-pencil' },
{ xtype :'button', text :'chat2', iconCls:'icon-chat2' },
{ xtype :'button', text :'retweet', iconCls:'icon-retweet' },
{ xtype :'button', text :'search', iconCls:'icon-search' },
{ xtype :'button', text :'time', iconCls:'icon-time' },
{ xtype :'button', text :'switch', iconCls:'icon-switch' },
{ xtype :'button', text :'camera', iconCls:'icon-camera' },
{ xtype :'button', text :'chat', iconCls:'icon-chat' },
{ xtype :'button', text :'settings2', iconCls:'icon-settings2' },
{ xtype :'button', text :'settings', iconCls:'icon-settings' },
{ xtype :'button', text :'tags', iconCls:'icon-tags' },
{ xtype :'button', text :'attachment2', iconCls:'icon-attachment2' },
{ xtype :'button', text :'bird', iconCls:'icon-bird' },
{ xtype :'button', text :'cloud', iconCls:'icon-cloud' },
{ xtype :'button', text :'delete_black1', iconCls:'icon-delete_black1' },
{ xtype :'button', text :'eye', iconCls:'icon-eye' },
{ xtype :'button', text :'file', iconCls:'icon-file' },
{ xtype :'button', text :'browser', iconCls:'icon-browser' },
{ xtype :'button', text :'home', iconCls:'icon-home' },
{ xtype :'button', text :'inbox', iconCls:'icon-inbox' },
{ xtype :'button', text :'network', iconCls:'icon-network' },
{ xtype :'button', text :'key', iconCls:'icon-key' },
{ xtype :'button', text :'radio', iconCls:'icon-radio' },
{ xtype :'button', text :'mail', iconCls:'icon-mail' },
{ xtype :'button', text :'news', iconCls:'icon-news' },
{ xtype :'button', text :'case', iconCls:'icon-case' },
{ xtype :'button', text :'photos', iconCls:'icon-photos' },
{ xtype :'button', text :'power', iconCls:'icon-power' },
{ xtype :'button', text :'action', iconCls:'icon-action' },
{ xtype :'button', text :'favorites', iconCls:'icon-favorites' },
{ xtype :'button', text :'plane', iconCls:'icon-plane' },
{ xtype :'button', text :'user', iconCls:'icon-user' },
{ xtype :'button', text :'video', iconCls:'icon-video' },
{ xtype :'button', text :'compose', iconCls:'icon-compose' },
{ xtype :'button', text :'truck', iconCls:'icon-truck' },
{ xtype :'button', text :'chart2', iconCls:'icon-chart2' },
{ xtype :'button', text :'chart', iconCls:'icon-chart' },
{ xtype :'button', text :'expand', iconCls:'icon-expand' },
{ xtype :'button', text :'refresh', iconCls:'icon-refresh' },
{ xtype :'button', text :'check', iconCls:'icon-check' },
{ xtype :'button', text :'check2', iconCls:'icon-check2' },
{ xtype :'button', text :'play', iconCls:'icon-play' },
{ xtype :'button', text :'pause', iconCls:'icon-pause' },
{ xtype :'button', text :'stop', iconCls:'icon-stop' },
{ xtype :'button', text :'forward', iconCls:'icon-forward' },
{ xtype :'button', text :'rewind', iconCls:'icon-rewind' },
{ xtype :'button', text :'play2', iconCls:'icon-play2' },
{ xtype :'button', text :'refresh2', iconCls:'icon-refresh2' },
{ xtype :'button', text :'minus', iconCls:'icon-minus' },
{ xtype :'button', text :'battery', iconCls:'icon-battery' },
{ xtype :'button', text :'left', iconCls:'icon-left' },
{ xtype :'button', text :'right', iconCls:'icon-right' },
{ xtype :'button', text :'calendar', iconCls:'icon-calendar' },
{ xtype :'button', text :'shuffle', iconCls:'icon-shuffle' },
{ xtype :'button', text :'wireless', iconCls:'icon-wireless' },
{ xtype :'button', text :'speedometer', iconCls:'icon-speedometer' },
{ xtype :'button', text :'more', iconCls:'icon-more' },
{ xtype :'button', text :'print', iconCls:'icon-print' },
{ xtype :'button', text :'download', iconCls:'icon-download' },
{ xtype :'button', text :'warning_black', iconCls:'icon-warning_black' },
{ xtype :'button', text :'locate', iconCls:'icon-locate' },
{ xtype :'button', text :'trash', iconCls:'icon-trash' },
{ xtype :'button', text :'cart', iconCls:'icon-cart' },
{ xtype :'button', text :'bank', iconCls:'icon-bank' },
{ xtype :'button', text :'flag', iconCls:'icon-flag' },
{ xtype :'button', text :'add', iconCls:'icon-add' },
{ xtype :'button', text :'delete', iconCls:'icon-delete' },
{ xtype :'button', text :'lock', iconCls:'icon-lock' },
{ xtype :'button', text :'unlock', iconCls:'icon-unlock' },
{ xtype :'button', text :'minus2', iconCls:'icon-minus2' },
{ xtype :'button', text :'add2', iconCls:'icon-add2' },
{ xtype :'button', text :'up', iconCls:'icon-up' },
{ xtype :'button', text :'down', iconCls:'icon-down' },
{ xtype :'button', text :'screens', iconCls:'icon-screens' },
{ xtype :'button', text :'bell', iconCls:'icon-bell' },
{ xtype :'button', text :'quote', iconCls:'icon-quote' },
{ xtype :'button', text :'volume_mute', iconCls:'icon-volume_mute' },
{ xtype :'button', text :'volume', iconCls:'icon-volume' },
{ xtype :'button', text :'help', iconCls:'icon-help' }
    ]
  }
});